/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package finalproject;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author rsexton17
 */
public class UserInterface extends javax.swing.JFrame {

    Items key;
    
    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
        try{
            key = new Items();
        }
        catch (MalformedURLException ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listOfItems = new javax.swing.JComboBox();
        accesInternet = new javax.swing.JButton();
        introLabel = new javax.swing.JLabel();
        txtAddCategory = new javax.swing.JTextField();
        addTopicButton = new javax.swing.JButton();
        txtAddURL = new javax.swing.JTextField();
        lblEdition = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listOfItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brakes", "Changing Oil", "Changing Tires", "Differentials", "Engine (Diesel)", "Engine (Gasoline)", "Exhaust", "Forced Induction (Super)", "Forced Induction (Turbo)", "Oil", "Rotating Tires", "Steering Column", "Suspension", "Transmission (Auto)", "Transmission (Manual)", "Wheels", " " }));
        listOfItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfItemsActionPerformed(evt);
            }
        });

        accesInternet.setText("Select");
        accesInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesInternetActionPerformed(evt);
            }
        });

        introLabel.setText("Select a topic:");

        txtAddCategory.setText("Add category");
        txtAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddCategoryActionPerformed(evt);
            }
        });

        addTopicButton.setText("Add");
        addTopicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTopicButtonActionPerformed(evt);
            }
        });

        txtAddURL.setText("Add URL");

        lblEdition.setText("Add a new topic:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(introLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accesInternet))
                    .addComponent(txtAddURL, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdition)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTopicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(introLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesInternet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEdition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTopicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(txtAddURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listOfItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfItemsActionPerformed
        listOfItems.getSelectedItem().toString();
        
    }//GEN-LAST:event_listOfItemsActionPerformed

    private void accesInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesInternetActionPerformed
        try {
            key.accessFiles(listOfItems.getSelectedItem().toString());
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accesInternetActionPerformed

    private void txtAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddCategoryActionPerformed
        /*String s = txtAddCategory.getText();
        URL url = null;
        try {
            url = new URL(txtAddURL.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        key.addTo(s, url);*/
    }//GEN-LAST:event_txtAddCategoryActionPerformed

    private void addTopicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTopicButtonActionPerformed
        String s = txtAddCategory.getText();
        URL url = null;
        try {
            url = new URL(txtAddURL.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            key.convert(url);
        } catch (URISyntaxException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        key.addTo(s, url);
        listOfItems.addItem(s);
    }//GEN-LAST:event_addTopicButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UserInterface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accesInternet;
    private javax.swing.JButton addTopicButton;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel lblEdition;
    private javax.swing.JComboBox listOfItems;
    private javax.swing.JTextField txtAddCategory;
    private javax.swing.JTextField txtAddURL;
    // End of variables declaration//GEN-END:variables
}
