/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pr2_7;

/**
 *
 * @author Riles175
 */
public class CookieInterface extends javax.swing.JFrame {

    Cookies c = new Cookies();
    
    /**
     * Creates new form CookieInterface
     */
    public CookieInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtThinMintInput = new javax.swing.JTextField();
        lblCookieSales = new javax.swing.JLabel();
        txtSamoaInput = new javax.swing.JTextField();
        txtChocolateChipInput = new javax.swing.JTextField();
        lblThinMints = new javax.swing.JLabel();
        lblSamoa = new javax.swing.JLabel();
        lblChocolateChips = new javax.swing.JLabel();
        calculateThinMints = new javax.swing.JButton();
        calculateSamoas = new javax.swing.JButton();
        calculateChocolateChips = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtThinMintInput.setText("Enter thin mints");

        lblCookieSales.setText("Cookie Sales");

        txtSamoaInput.setText("Enter samoas");

        txtChocolateChipInput.setText("Enter chocolate chips");

        lblThinMints.setText("Thin mint sales");

        lblSamoa.setText("Samoa sales");

        lblChocolateChips.setText("Chocolate chip sales");

        calculateThinMints.setText("Calculate thin mints");
        calculateThinMints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateThinMintsActionPerformed(evt);
            }
        });

        calculateSamoas.setText("Calculate samoas");
        calculateSamoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateSamoasActionPerformed(evt);
            }
        });

        calculateChocolateChips.setText("Calculate chocolate chips");
        calculateChocolateChips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateChocolateChipsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtThinMintInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblThinMints)
                        .addGap(18, 18, 18)
                        .addComponent(calculateThinMints))
                    .addComponent(lblCookieSales)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSamoaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSamoa)
                        .addGap(18, 18, 18)
                        .addComponent(calculateSamoas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtChocolateChipInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblChocolateChips)
                        .addGap(18, 18, 18)
                        .addComponent(calculateChocolateChips)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCookieSales)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThinMintInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThinMints)
                    .addComponent(calculateThinMints))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSamoaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSamoa)
                    .addComponent(calculateSamoas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChocolateChipInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChocolateChips)
                    .addComponent(calculateChocolateChips))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateThinMintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateThinMintsActionPerformed
        int i = Integer.parseInt(txtThinMintInput.getText());
        c.setThinMint(i);
        String f = String.format("%d", (int)c.thinMintSales());
        lblThinMints.setText("$ " + f);
    }//GEN-LAST:event_calculateThinMintsActionPerformed

    private void calculateSamoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateSamoasActionPerformed
         int i = Integer.parseInt(txtSamoaInput.getText());
        c.setSamoa(i);
        String f = String.format("%d", (int)c.samoaSales());
        lblSamoa.setText("$ " + f);
    }//GEN-LAST:event_calculateSamoasActionPerformed

    private void calculateChocolateChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateChocolateChipsActionPerformed
        int i = Integer.parseInt(txtChocolateChipInput.getText());
        c.setChocolateChip(i);
        String f = String.format("%d", (int)c.chocolateChipSales());
        lblChocolateChips.setText("$ " + f);
    }//GEN-LAST:event_calculateChocolateChipsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookieInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookieInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookieInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookieInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CookieInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateChocolateChips;
    private javax.swing.JButton calculateSamoas;
    private javax.swing.JButton calculateThinMints;
    private javax.swing.JLabel lblChocolateChips;
    private javax.swing.JLabel lblCookieSales;
    private javax.swing.JLabel lblSamoa;
    private javax.swing.JLabel lblThinMints;
    private javax.swing.JTextField txtChocolateChipInput;
    private javax.swing.JTextField txtSamoaInput;
    private javax.swing.JTextField txtThinMintInput;
    // End of variables declaration//GEN-END:variables
}
